parameters: { }
environment: { }
packages:
  - name: salebot
    shared: false
    environment: { }
    parameters: { }
    annotations: { }
    functions:
      - name: proxy
        binary: false
        runtime: "go:1.20"
        main: ""
        web: true
        webSecure: false
        environment:
          CONSTRUCTOR_URL: "${CONSTRUCTOR_URL}"
          TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
        annotations: { }
        parameters: { }
