name: Code quality check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'

      - run: go get ./packages/salebot/proxy/

      - run: >
          go mod tidy 
          && git diff --exit-code

      - run: go mod download

      - run: go mod verify

      - run: go vet ./packages/salebot/proxy/

      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Go test
        run: >
          GORACE="atexit_sleep_ms=0" go test 
          -v
          -count=1
          -shuffle=on
          -race
          -coverprofile=coverage.txt
          -covermode=atomic
          ./packages/salebot/proxy/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        continue-on-error: true
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
          fail_ci_if_error: false
